title: Piotr Leniec's blog
header-img: img/home-bg.jpg
email: leniec.piotr@gmail.com
description:
baseurl:
url: https://leniec.com
twitter_username:
github_username: piotrleniec
facebook_username:
email_username: leniec.piotr@gmail.com
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
paginate: 5
author: Piotr Leniec
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
